### ISSUE TITLE
Add a usage or help screen

### ISSUE THREAD

**Issue by benji011** [chfritz/lineselect#4]
This also happens if I try to just execute `lineselect`. 
But I'm expecting a help message to show like other commands like `gh` does

```bash
❯ lineselect --help
fs.js:618
  handleErrorFromBinding(ctx);
  ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:618:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at file:///Users/benji.lo/.nvm/versions/node/v14.21.1/lib/node_modules/lineselect/dist/cli.js:7:17
    at <anonymous> (<anonymous>) {
  errno: -35,
  syscall: 'read',
  code: 'EAGAIN'
}
```

**Comment by chfritz** [comment]
Thanks for the suggestion. Yes, you are probably right, we should add a help screen. PR welcome, otherwise I'll try to add it soon.
